# Generated by Django 4.0.5 on 2022-06-29 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='subcatgeory',
            new_name='subcategory',
        ),
    ]
